FROM jenkins/jenkins:2.387.3-lts-jdk11

USER root

# Install Docker CLI and other useful tools
RUN apt-get update && \
    apt-get install -y docker.io curl git wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Add Jenkins user to the Docker group
RUN usermod -aG docker jenkins

USER jenkins